### ISSUE TITLE
Run BC version 17 in docker. Running Business Central code compatible with BC 17 not working on previous versions of BC 16.3

### ISSUE THREAD

**Issue by tartino** [HodorNV/ALOps#244]
**Bug**
We are currently expiriencing issues compiling BC code version 17 in docker image sandbox:gb-ltsc2019. This is causing the following compilation error:

![image](https://user-images.githubusercontent.com/24921182/97897305-32a04f00-1d2e-11eb-90cf-f8aa983cd01e.png)

In order to resolve the issue we have tried to upgrade the version of the docker image to the newer  version of BC
https://bcartifacts.azureedge.net/sandbox/17.0.17126.18434/gb

The above does not seem to be a valid docker registry and when running the pipeline we get the following error

![image](https://user-images.githubusercontent.com/24921182/97897617-a5a9c580-1d2e-11eb-88fa-3fc3a594087b.png)

**Used yaml**
```yaml
         - task: ALOpsDockerStart@1
            displayName: 'ALOps Docker Start'
            inputs:
              docker_image: 'https://bcartifacts.azureedge.net/sandbox/17.0.17126.18434/gb'
              accept_image_outdated: true
              enable_symbol_loading: true
              memory_gb: 6
              docker_pull: true
              container_restart: always
              docker_parameters: '--isolation=hyperv'

          - task: ALOpsDockerWait@1
            inputs:
              search_string: 'Ready for connections!'

          - task: ALOpsLicenseImport@1
            inputs:
              usedocker: true
              license_path: $(bcdeploylicense)
```

**Expected behaviour**
I would like to understand how I can update the alops extension to use the latest version of BC 17

Thanks

**Comment by MortenRa** [comment]
Try to add this step before the ALOpsDockerStart step 
```

  - task: ALOpsDockerCreate@1
    displayName: 'Create Docker Image'
    inputs:
        artifacttype: Sandbox
        artifactcountry: 'gb'


  - task: ALOpsDockerStart@1
    displayName: 'ALOps Docker Start'
    inputs:
      accept_image_outdated: true
      enable_symbol_loading: true
      memory_gb: 6
      docker_pull: true
      container_restart: always
      docker_parameters: '--isolation=hyperv'

```

**Comment by tartino** [comment]
How will I define the image version using the above?

**Comment by MortenRa** [comment]
> How will I define the image version using the above?

This will always take the latest released version : https://github.com/HodorNV/ALOps/blob/master/Examples/ArtifactVersions/01_LatestReleased.yml

if you need a specific version you can add 
https://github.com/HodorNV/ALOps/blob/master/Examples/ArtifactVersions/02_SpecificVersion.yml

artifactversion: 17.0

**Comment by waldo1001** [comment]
Hi @tartino ,

is your issue solved with the above?

**Comment by tartino** [comment]
Thanks all,

This was resolved as suggested by @MortenRa 

 ```
         - task: ALOpsDockerCreate@1
            displayName: 'ALOPS - Create Docker Image'
            inputs:
              artifactversion: '17.0'
              artifacttype: Sandbox
              artifactcountry: 'gb'

          - task: ALOpsDockerStart@1
            displayName: 'ALOps Docker Start'
            inputs:
              accept_image_outdated: true
              enable_symbol_loading: true
              memory_gb: 6
              docker_parameters: '--isolation=hyperv'

          - task: ALOpsDockerWait@1
            inputs:
              search_string: 'Ready for connections!'
```

Thank you for your help. This can be closed
